# Generated by Django 5.2.13 on 2026-05-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chatmessage_attachment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('processed', 'Đang xử lý'), ('done', 'Hoàn tất'), ('archived', 'Lưu trữ')], default='new', max_length=20),
        ),
    ]
