# Generated by Django 5.2.13 on 2026-05-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_consultationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Hình ảnh'), ('document', 'Tài liệu'), ('video', 'Video'), ('audio', 'Âm thanh')], max_length=50, null=True, verbose_name='Loại tệp đính kèm'),
        ),
    ]
